name: Deploy to container registry

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REPOSITORY: ${{ secrets.DOCKER_REGISTRY }}/discordpollbot

    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build . -t $REPOSITORY:${GITHUB_REF:10}
      - run: docker push $REPOSITORY:${GITHUB_REF:10}
